# Generated by Django 3.1.6 on 2021-05-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capasity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='slot',
            name='event_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
