# Generated by Django 3.1.6 on 2021-05-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210512_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capasity',
            old_name='name',
            new_name='capasity',
        ),
    ]
