# Generated by Django 3.1.6 on 2021-05-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210512_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='event_type',
            field=models.CharField(choices=[('Enter', 'Enter'), ('Exit', 'Exit')], max_length=200, null=True),
        ),
    ]
