# Generated by Django 3.1.6 on 2021-05-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210513_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='date_created',
            new_name='date_happened',
        ),
    ]
