# Generated by Django 3.1.6 on 2021-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210513_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('free_slots', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Capasity',
        ),
    ]
