# Generated by Django 3.1.6 on 2021-05-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210515_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacity',
            name='free_slots',
        ),
    ]
