# Generated by Django 3.1.6 on 2021-05-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_capacity_free_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
