# Generated by Django 3.1.6 on 2021-05-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_slot_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='note',
        ),
    ]
